//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reversi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reversi.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black move.
        /// </summary>
        public static string rsBlackMove {
            get {
                return ResourceManager.GetString("rsBlackMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black won.
        /// </summary>
        public static string rsBlacksWon {
            get {
                return ResourceManager.GetString("rsBlacksWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string rsCancel {
            get {
                return ResourceManager.GetString("rsCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faster AI.
        /// </summary>
        public static string rsFasterAI {
            get {
                return ResourceManager.GetString("rsFasterAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active game is in progress.
        ///Are you sure, you want to start a new one?.
        /// </summary>
        public static string rsGameInProgress {
            get {
                return ResourceManager.GetString("rsGameInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string rsOK {
            get {
                return ResourceManager.GetString("rsOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select game players:.
        /// </summary>
        public static string rsSelectPlayers {
            get {
                return ResourceManager.GetString("rsSelectPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        public static string rsStartNewGame {
            get {
                return ResourceManager.GetString("rsStartNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tie.
        /// </summary>
        public static string rsTie {
            get {
                return ResourceManager.GetString("rsTie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White move.
        /// </summary>
        public static string rsWhiteMove {
            get {
                return ResourceManager.GetString("rsWhiteMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White won.
        /// </summary>
        public static string rsWhitesWon {
            get {
                return ResourceManager.GetString("rsWhitesWon", resourceCulture);
            }
        }
    }
}
